# Generated by Django 2.2.7 on 2019-11-24 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='created_date',
        ),
    ]
